### ISSUE TITLE
[BUG]: Can't get the API key from Developer area - greyed out.

### ISSUE THREAD

**Issue by easaw** [getlago/lago#127] opened 2022-11-07 20:24 UTC
**Describe the bug**
I have installed Lago locally and the API box in `/developpers` does not copy. When using inspect it seems there is no API key there at all???

_Also, 'developpers' is spelt wrong in the URL..._

**To Reproduce**
Steps to reproduce the behaviour:
1. Install locally
2. Click on Developers
3. Try to click Copy next to API Key
4. Nothing happens

When I use inspect, they API key is just `value="••••••••••••••••••••••••••••927"` literally bullet points.

**Support**
 - OS: MacOS
 - Browser: Chrome
 - Version: 107 (latest)

**Additional context**
Server: Ubuntu 20.04.5 LTS / Docker 20.10.21

Also, when trying to delete a customer;
> "This customer can’t be deleted because she’s linked to an active or terminated existing subscription"

Why does it say "she" instead of just "they" as a general term for everyone?
Especially as one "customer" could be a group of people, or another company, so using "They" or "They're" would be more appropriate.

**Comment by mathieu-lago** [comment] 2022-11-08 09:10
Hi @easaw - thanks for opening this ticket.

Our engineering team is looking into this and will soon release a corrected version. We will let you know when this is fixed.

We will also modify the copies according to your recommendations.

**Comment by ansmonjol** [comment] 2022-11-08 10:13
Hello @easaw, I'm looking at the "copy to clipboard" issue you've reported above.

This can happen if you run the frontend application on a "non secure" environment, that prevents Chrome to access the clipboard.
Can you please make sure you run your application with secure origin such as `https` or `localhost` ?
Other reason could be that you have disabled your browser to allow access to the clipboard, which is a manual action.

Can you check on your side if those are the causes ?

Anyway, we should improve the "copy to clipboard" actions in the app IMO:
- If there is no reason to hide the data, it should be fully displayed in the screen
- If the clipboard API is not available, we should display an error message on button click.

I've created [an improvement](https://github.com/getlago/lago-front/issues/553) for this to be applied on all "copy to clipboard" of the app.

Please let me know how it went.

---

Further infos
- [Clipboard interface](https://w3c.github.io/clipboard-apis/#clipboard-item-interface) spec that shows it uses the SecureContext
- [Secure context definition](https://developer.mozilla.org/en-US/docs/Web/Security/Secure_Contexts)
- A way we could [handle the clipboard API status](https://stackabuse.com/how-to-copy-to-clipboard-in-javascript-with-the-clipboard-api/)

**Comment by easaw** [comment] 2022-11-08 14:12
> Hello @easaw, I'm looking at the "copy to clipboard" issue you've reported above.
> 
> This can happen if you run the frontend application on a "non secure" environment, that prevents Chrome to access the clipboard. Can you please make sure you run your application with secure origin such as `https` or `localhost` ? Other reason could be that you have disabled your browser to allow access to the clipboard, which is a manual action.
> 
> Can you check on your side if those are the causes ?
> 

Hi,

I was/ will be running locally, yes, when you say 'localhost', I assume you mean on my machine, and not on another machine (but still on an internal network)?
Currently I am using "lago.demoserver.local" with the IP address in /etc/hosts, do I need to run it specifically on my machine?

Also, would it be a good idea to run it on docker desktop?

I have also had trouble running it on a 2GB VPS on Linode, what are the minimum server requirements?

I tried googling "lago minimum server requirements" but there didn't seem to be any details :(

Thank you.

P.S.

> * If there is no reason to hide the data, it should be fully displayed in the screen

sounds like a good idea to me as well 👍

**Comment by jdenquin** [comment] 2022-11-09 09:51
Hello @easaw 

2GB seems a bit light in term of RAM to run the full application in a production environment, depending on your volume of usage.
If you just want to try Lago, you can run it on Docker Desktop on your local machine of course.

**Comment by ansmonjol** [comment] 2022-11-10 10:17
Hey @easaw,

You can find fixes for the issues you described initially in the last release [`v0.14.0-alpha`](https://github.com/getlago/lago/releases/tag/v0.14.0-alpha)
- API key not visible in developer section
- Developer typo
- Copy usage of she instead of they

The ability to know when copy-to-clipboard fails will be handled in a separate improvement. You can follow it's enhancement [here](https://github.com/getlago/lago-front/issues/553)

I'll close this ticket. If you feel we missed something feel free to comment here !

**Closed as completed by ansmonjol** 2022-11-10 10:17 UTC
Labels: issue: bug
