### ISSUE TITLE
[BUG]: CORS prevents signup when running locally via `docker-compose up`

### ISSUE THREAD

**Issue by theronic** [getlago/lago#251] opened 2023-06-27 09:16 UTC
(edit: accurate compose command to overrides ports)

**Describe the bug**

Access to fetch at 'http://localhost:3000/graphql' from origin 'http://localhost:8081' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

**To Reproduce**

```
gh repo clone getlago/lago
FRONT_URL=http://localhost:8081 POSTGRES_PORT=5433 FRONT_PORT=8081 docker-compose up
```

Now open frontend on port 8081 and try to sign up. Frontend loads but API doesn't start because Postgres doesn't start.

**Expected behavior**
should not fail

**Screenshots**
![image](https://github.com/getlago/lago/assets/1011676/c0fcdcb0-587f-4dfa-bea1-f33dfe9aeb92)

**Support**
macOS, Brave.

**Comment by theronic** [comment] 2023-06-27 09:24
Note: I did set `FRONT_URL` which should feed into the rake-cors CORS settings.

Command to run:
```
FRONT_URL=http://localhost:8081 POSTGRES_PORT=5433 FRONT_PORT=8081 docker-compose up
```

(Aside: docker-compose does not exit when I press Ctrl+C.)

**Comment by theronic** [comment] 2023-06-27 09:56
Hmmk so FRONT_URL was setting CORS settings but Postgres was not starting even though POSTGRES_PORT was set.

So new bug: Lago does not honour POSTGRES_PORT override, or maybe Postgres refuses to start. Probably port mapping issue.

**Comment by jdenquin** [comment] 2023-06-28 08:08
@theronic so the CORS issue is resolved?
It's always around the `LAGO_FRONT_URL` defintion for the `api` service for this kind of errors, we will add more info on the doc about this.

Can you share some errors or informations about the `POSTGRES_PORT` issue? On the code side, backend don't know about port because we use `DATABASE_URL` so everything is around the docker configuration here!

**Comment by jdenquin** [comment] 2023-06-29 08:01
just adding, can you check that you are on the `main` branch of the repo? Github had a bug yesterday and was routing by default to an other branch

**Comment by Alexey2257** [comment] 2023-07-01 09:36
The issue is seemed to be in api environment, we should use 5432 port here, not port from env
works for me while using POSTGRES_PORT=5433:

`      - DATABASE_URL=postgresql://${POSTGRES_USER:-lago}:${POSTGRES_PASSWORD:-changeme}@db:5432/${POSTGRES_DB:-lago}`

**Comment by jdenquin** [comment] 2023-07-05 09:27
if you use the `5432` port in the docker network yes, I'll update the `docker-compose` file this way

```yaml
ports:
      - ${POSTGRES_PORT:-5432}:${POSTGRES_PORT:-5432}
```

**Comment by jdenquin** [comment] 2023-07-07 09:44
fixed in https://github.com/getlago/lago/pull/254

**Closed as completed by jdenquin** 2023-07-07 09:44 UTC
Labels: issue: help wanted
